- name: ping server
  ping:

- name: Download and Install kibana
  apt:
    deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.14-amd64.deb 

- name: Copy config file for kibana
  copy:
    src: /home/user/kurs/ansible/roles/kibana/files/kibana.yml
    dest: /etc/kibana
    mode: 0644
    owner: user
    group: root

- name: restarted kibana
  service:
    name: kibana
    state: restarted   

- name: systemctl enable kibana
  ansible.builtin.service:
    name: kibana
    enabled: yes